### ISSUE TITLE
non-op can´t break snow!

### ISSUE THREAD

**Issue by PetyXbron** [thebigsmileXD/Spleef#5]
So, I have the default settigns after the arena create,
aaand.... the non-op players, cant break any blocks...
yeah. I thaught it was bcause spawn protect, but its not this problem.
I have in the world config set the "can break block id" 80, but it dont works :(

**Comment by inxomnyaa** [comment]
There once was a bug with the selected slot - try changing to an empty hotbar slot and back to the shovel

The permissions have not been changed in years. Make sure plugins like MultiWorld don't cause this issue.

Can not reproduce

**Comment by inxomnyaa** [comment]
Have you figured out the issue? Could you please update me what it was?

**Comment by PetyXbron** [comment]
I'm so sorry, I decided that I no longer want to spleef on my server
